#!/usr/bin/env bash
# Concatenates the pending migrations into one file for the Supabase SQL Editor.
# Regenerate after editing any migration: ./supabase/build-combined.sh
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
mkdir -p supabase/dist
OUT=supabase/dist/apply-all.sql
{
  cat <<'HDR'
-- ═══════════════════════════════════════════════════════════════════
-- Lia — all pending migrations, in order, as one script.
--
-- GENERATED by supabase/build-combined.sh. Do not edit by hand; edit the
-- individual migrations and regenerate.
--
-- Paste the whole thing into the Supabase SQL Editor and run it once. Every
-- statement is idempotent, so re-running is safe.
--
-- Applies: 03 accounts/billing · 04 versioned inspections · 05 rep numbers
--          06 fall protection · 07 status · 08 device snapshot · 09 authoring
--
-- 10_consolidate_account.sql is deliberately NOT included. It is optional, it
-- only suits a single-company deployment, and it needs a user id — see
-- docs/APPLY-MIGRATIONS.md.
--
-- Read the NOTICEs afterwards. 04 reports any inspection whose account it could
-- not work out; those rows stay invisible to the app until assigned.
-- ═══════════════════════════════════════════════════════════════════
HDR
  for f in supabase/0[3-9]_*.sql; do
    printf '\n-- ┌───────────────────────────────────────────────────────────────────\n'
    printf -- '-- │ %s\n' "$(basename "$f")"
    printf -- '-- └───────────────────────────────────────────────────────────────────\n\n'
    cat "$f"
  done
} > "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
