#!/usr/bin/env bash
# Write supabase/schema.sql — what the database looks like once every migration
# has run. One file to read instead of twenty-two to piece together.
#
#   ./supabase/tools/schema-snapshot.sh           # regenerate
#   ./supabase/tools/schema-snapshot.sh --check   # fail if it is out of date
#
# It is DERIVED, never edited: built by applying the migrations in order to a
# throwaway database and dumping the result. That is also what makes it
# trustworthy — it is what the SQL actually produces, not what someone believed
# it produced.
#
# It is not a way to create the live database. The live database is changed by
# pasting migrations into the SQL editor, and a dump cannot be pasted at a
# database that already holds records. This file answers "what shape is it now",
# which is the question the migration files answer badly.
set -euo pipefail

DB="${LIA_SCHEMA_DB:-lia_schema_snapshot}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SUPA="$(dirname "$HERE")"
MIG="$SUPA/migrations"
OUT="$SUPA/schema.sql"

for p in /opt/homebrew/opt/postgresql@16/bin /opt/homebrew/bin /usr/local/bin; do
  [ -d "$p" ] && PATH="$p:$PATH"
done

pg_isready -q || { echo "No local Postgres. Try: brew services start postgresql@16" >&2; exit 1; }

psql -q -d postgres -c "DROP DATABASE IF EXISTS $DB;" -c "CREATE DATABASE $DB;"
trap 'psql -q -d postgres -c "DROP DATABASE IF EXISTS $DB;" >/dev/null 2>&1' EXIT

# The same stubs the test harness uses: Supabase provides auth.users, auth.uid()
# and the anon/authenticated roles, and the migrations reference them.
# The migrations are idempotent, so they narrate what they skipped. That is
# useful when applying for real and pure noise here.
export PGOPTIONS='--client-min-messages=warning'

psql -q -v ON_ERROR_STOP=1 -d "$DB" -f "$SUPA/test/00_stub_supabase.sql" >/dev/null
for f in "$MIG"/[0-9][0-9]_*.sql; do
  psql -q -v ON_ERROR_STOP=1 -d "$DB" -f "$f" >/dev/null
done

TMP="$(mktemp -t lia-schema)"
{
  cat <<HDR
-- ═══════════════════════════════════════════════════════════════════
-- Lia — the database, as the migrations leave it.
--
-- GENERATED by supabase/tools/schema-snapshot.sh. Do not edit: edit the
-- migration that owns the thing you want to change, then regenerate.
--
-- Read this to answer "what tables, policies, functions and grants exist".
-- It is NOT how the live database is changed — that is a migration pasted into
-- the Supabase SQL editor, because a dump cannot be applied to a database that
-- already holds records.
--
-- Migrations included: $(ls "$MIG"/[0-9][0-9]_*.sql | wc -l | tr -d ' ')
-- Grants and RLS policies are included deliberately: "anon cannot read
-- inspections" is a property of this file, not a footnote.
-- ═══════════════════════════════════════════════════════════════════

HDR
  # --no-owner: ownership is a local artifact. Privileges are KEPT, because the
  # REVOKEs are load-bearing security, not noise.
  # \restrict / \unrestrict carry a token pg_dump randomises per run (PG 16+),
  # which would make every regeneration look like a change.
  pg_dump --schema-only --no-owner --schema=public "$DB" \
    | grep -vE '^\\(un)?restrict '
} > "$TMP"

if [ "${1:-}" = "--check" ]; then
  if ! diff -q "$OUT" "$TMP" >/dev/null 2>&1; then
    echo "schema.sql is out of date. Run ./supabase/tools/schema-snapshot.sh" >&2
    diff "$OUT" "$TMP" | head -40 >&2 || true
    rm -f "$TMP"
    exit 1
  fi
  rm -f "$TMP"
  echo "schema.sql is current."
  exit 0
fi

mv "$TMP" "$OUT"
echo "Wrote $OUT ($(wc -l < "$OUT" | tr -d ' ') lines)"
